// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  java.util.List<Receipt>
      getReceiptsList();
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  Receipt getReceipts(int index);
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  int getReceiptsCount();
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  java.util.List<? extends ReceiptOrBuilder>
      getReceiptsOrBuilderList();
  /**
   * <code>repeated .api.Receipt receipts = 1;</code>
   */
  ReceiptOrBuilder getReceiptsOrBuilder(
          int index);
}
