// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/api.proto

package io.grpc.bverify;

public interface GetForwardedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.GetForwardedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.IssueReceiptRequest issue_receipt = 1;</code>
   */
  boolean hasIssueReceipt();
  /**
   * <code>.api.IssueReceiptRequest issue_receipt = 1;</code>
   */
  IssueReceiptRequest getIssueReceipt();
  /**
   * <code>.api.IssueReceiptRequest issue_receipt = 1;</code>
   */
  IssueReceiptRequestOrBuilder getIssueReceiptOrBuilder();

  /**
   * <code>.api.TransferReceiptRequest transfer_receipt = 2;</code>
   */
  boolean hasTransferReceipt();
  /**
   * <code>.api.TransferReceiptRequest transfer_receipt = 2;</code>
   */
  TransferReceiptRequest getTransferReceipt();
  /**
   * <code>.api.TransferReceiptRequest transfer_receipt = 2;</code>
   */
  TransferReceiptRequestOrBuilder getTransferReceiptOrBuilder();

  public GetForwardedResponse.RequestCase getRequestCase();
}
